#Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: 8fzPA9jCuntNmDKjf/RWRvEQuqqsuMNJ7ywZ2hIWnbrETAWc9JtW3PnhEhnRXaIU

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

install:
  - ps: Get-PackageProvider -Name NuGet -ForceBootstrap
  - ps: Install-Module Pester -MinimumVersion '3.4.0' -force
  - ps: Install-Module Psake, PSDeploy, BuildHelpers, PlatyPS, PSScriptAnalyzer -force
  - ps: Import-Module Psake, BuildHelpers, PlatyPS, PSDeploy, Pester -force

skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#before_test:
#  - ps: . .\Build.ps1

test_script:
  - ps: Invoke-psake .\Build.Psake.ps1
